sidekiq:
  build: docker/sidekiq
  command: bundle exec foreman s
  ports:
   - "3000:3000"
  volumes:
   - .:/opt/pikabu_crawler
  links:
   - redis
   - elastic
redis:
  image: redis:3.0
  command: redis-server --appendonly yes
  ports:
   - "6379:6379"
  volumes:
    - ./data/redis:/data
elastic:
  build: docker/elastic
  command: elasticsearch -Des.network.host=0.0.0.0
  privileged: true
  ulimits:
    memlock:
      soft: -1
      hard: -1
  volumes:
    - ./data/elastic:/usr/share/elasticsearch/data
    - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
nginx:
  image: nginx:stable
  command: nginx
  ports:
    - "9200:9200"
    - "3001:3001"
  links:
    - elastic
  volumes:
    - ./frontend/dist:/opt/frontend
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
